AllCops: 
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - config/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

require:
    - rubocop-rails

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "**/*_api.rb"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Enabled: false
  # Max: 100

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - "**/**.rb"

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
